#!/bin/sh -eu

PIDFILE=/var/run/minidlna/minidlna.pid
INTERVAL=${MINIDLNA_REBUILD_INTERVAL:-300}

# Remove old pid file if it exists.
[ -f $PIDFILE ] && rm -f $PIDFILE

# Start a minidlnad in background.
/usr/local/sbin/minidlnad -f /etc/minidlna.conf -P $PIDFILE -S &

# Rebuild the index periodically.
while true;
do
    sleep $INTERVAL
    /usr/local/sbin/minidlnad -f /etc/minidlna.conf -P $PIDFILE -U
done
