name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-cache-${{ hashFiles('Dockerfile', 'run-minidlna') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: >-
            linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8,
          tags: mirakc/minidlna:latest
          cache-from: |
            type=local,src=/tmp/.docker-cache
          cache-to: |
            type=local,dest=/tmp/.docker-cache-new
          push: true
      - name: Move cache
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
